apiVersion: v2
# Name of this Helm chart
name: example-deployment
# Description of this Helm chart
description: Helm chart used to deploy and manage a scaled pod running a given container image.
# Helm chart application
type: application
# Version of this helm chart (see https://github.com/startxfr/helm-repository/blob/dev/README.md for helm chart release guidelines)
version: 12.36.58-noschema
  - kubernetes
  - helm
  - startx
  - example-chart
  - example
  - caas
  - deployment
  - apache
  - html
  - web static
# STARTX helm chart repository homepage
home: https://helm-repository.readthedocs.io/en/latest
# Sources and documentation for this chart
sources:
  - https://helm-repository.readthedocs.io/en/latest/charts/example-sxapi
  - https://github.com/startxfr/helm-repository/tree/master/charts/example-sxapi
# Main maintainer contact for this helm chart
maintainers: 
  - name: "STARTX"
    email: "dev@startx.fr"
    url: "https://www.startx.fr"

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "release 12.36.58 aligned with OCP 4.12.36"
  artifacthub.io/containsSecurityUpdates: "false"